### ISSUE TITLE
Help page CSS

### ISSUE THREAD

**Issue by DirkHeinke** [DevWars/dev-wars#8]
On the help page, the sidebar collides with the footer, if you scroll down.
![devwarshelpscroll](https://cloud.githubusercontent.com/assets/5230945/8354862/9daaad08-1b4b-11e5-9ec4-6a595b04e014.png)

Also, if you load the help page with the link from the frontpage, it will scroll to the middle of the TOC.

**Comment by BeauAgst** [comment]
Thanks Dirk, this should be fixed now! Let me know if there's any more problems.

**Comment by DirkHeinke** [comment]
Already pushed to production? I still see the same issues there.

**Comment by BeauAgst** [comment]
No not yet, it'll be pushed to production at a later date.
